### ISSUE TITLE
Cannot generate setupURI on an accessory that isn't published yet!

### ISSUE THREAD

**Issue by Mil100057** [slonoed/homebridge-synology-surveillance-homemode#1]
Hello,

could it be that there is an issue with Node 20.X.X ?
The module does not want to start.

------------------------------------------------
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11730:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at HomeMode.json (/var/lib/homebridge/node_modules/@slonoed/homebridge-synology-surveillance-homemode/index.js:130:22)
    at HomeMode.getInfo (/var/lib/homebridge/node_modules/@slonoed/homebridge-synology-surveillance-homemode/index.js:118:20)
    at HomeMode.getSid (/var/lib/homebridge/node_modules/@slonoed/homebridge-synology-surveillance-homemode/index.js:93:18)
[27/11/2023, 12:59:35] Got SIGTERM, shutting down Homebridge...
[27/11/2023, 12:59:35] AssertionError [ERR_ASSERTION]: Cannot generate setupURI on an accessory that isn't published yet!
    at Bridge.Accessory.setupURI (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:994:11)
    at Server.setServerStatus (/var/lib/homebridge/node_modules/homebridge/src/server.ts:155:45)
    at Server.teardown (/var/lib/homebridge/node_modules/homebridge/src/server.ts:199:10)
    at signalHandler (/var/lib/homebridge/node_modules/homebridge/src/cli.ts:93:12)
    at process.emit (node:events:514:28)
    at process.emit (/var/lib/homebridge/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:516:21)
---------------------------------------------------
Homebridge config file:

"accessories": [
        {
            "accessory": "HomeMode",
            "name": "HomeMode",
            "host": "https://192.168.x.xx:5001/",
            "username": "mu-username",
            "password": "my_password"
        }
    ],

Thanks

**Comment by kbherbert** [comment]
I am having the same issue, only mine is with Node.js v18.16.0

```
OS	Ubuntu Jammy Jellyfish (22.04.3 LTS)
IPv4 (eth0)	redacted
IPv6 (eth0)	redacted
Hostname	raspberrypi
User	root
Node.js Version	 v18.16.0
Node.js Path	/opt/homebridge/bin
Storage Path	/var/lib/homebridge
Config Path	/var/lib/homebridge/config.json
Plugin Path	/var/lib/homebridge/node_modules
Timezone	GMT-0500
Docker	Yes
```

**Comment by senderversteller** [comment]
Same here on Node.js Version v20.15.0.

Can someone please fix it? I absolutely need a plugins in Homebridge to switch/control HomeMode on/off in Synology Surveillance Station. 

The other existing from [Plugins](https://github.com/jon-bell/homebridge-synology-surveillance-homemode) from jon-bell was working with DSM 6.x , also working some time with DSM 7.x with some modifications on index.js, but is no longer working.

**Comment by kbherbert** [comment]
Thanks again for sharing your plugin @slonoed! 🤓 I did some debugging, and narrowed down a couple of things, all of which I think could probably be remedied by some documentation and/or improved error handling (I will submit a PR for that). First of all:

1. Upgraded my Node.js version to `20.17.0`
2. Upgraded Homebridge installation to `v1.8.4` (I am running in a Docker container on a Raspberry Pi)

My issue came as a result of the way `new Url()` and `new URLSearchParams()` are handled. Slashes, and ports are important here. I also do not have a working cert on my Synology, so couldn't use TLS. So the config that worked for me was:

```json
  "accessory": "HomeMode",
  "name": "HomeMode",
  "host": "http://192.168.4.22:5000",
  "username": "homebridge1",
  "password": "*******"
```

In response to @Romeo1984's comment on #2, I worked around this simply by creating a dedicated api principal and user solely for use with Homebridge. Then just disable 2FA for that user. Then, following the principle of least privilege, create a minimal _Privilege Profile_ in DSM's Surveillance Station and assign them the "Manually Switch to Home Mode" role.

I also see the warnings in Homebridge logs about [2.0 readiness](https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0) and switching to the preferred [Dynamic Platform Plugin](https://developers.homebridge.io/#/api/platform-plugins) template. If you'd like to collaborate on that at some point, I'd be happy to help test @slonoed.

**Comment by slonoed** [comment]
Hi @kbherbert! Thank you for investigating. 
I do not work on this plugin currently. It works for me and I don't have time to accommodate other usages. I may have time in future but no promises. Said that I don't mind accept PRs and also don't mind if you just fork it and continue to work on it.

**Comment by Romeo1984** [comment]
@kbherbert Thank you for looking at this. I just now got around to experimenting with this. I got it to work like you suggested!
